@startuml
title Warmhouse Device Integration Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(WarmhouseSystem, "Warmhouse System") {
  Container(DeviceIntegration, "Device Integration", "Go", "Integrates with partner devices via various protocols")
  Container(EventBus, "Event Bus", "Apache Kafka", "Asynchronous communication between services")
}

Container(DeviceIntegration, "Device Integration", "Go") {
  Component(CommandExecutor, "Command Executor", "Executes commands to partner devices")
  Component(TelemetryReceiver, "Telemetry Receiver", "Receives telemetry from partner devices")
}

Rel(TelemetryReceiver,EventBus,"Telemetry update event")

@enduml