@startuml
title Warmhouse Device Registry Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(WarmhouseSystem, "Warmhouse System") {
  Container(DeviceRegistry, "Device Registry", "Go", "Device registration")
  Container(Database, "Database", "PostgreSQL", "Stores device data")
}

Container(DeviceRegistry, "Device Registry", "Go") {
  Component(ServiceLayer, "Service Layer", "Business logic")
  Component(RepositoryLayer, "Repository Layer", "Data access logic")
}

Rel(ServiceLayer,RepositoryLayer,"Reads/Writes device data")

Rel(RepositoryLayer,Database,"Reads/Writes device data")

@enduml